### ISSUE TITLE
Como fazer deploy

### ISSUE THREAD

**Issue by azrossi** [steffmartin/condominio#1]
Olá!
Eu precisaria de ajuda para testar o aplicativo de gestão de condomínio.
Você está disponível para serviço de assistência para o deploy do sistema?
Por favor entre em contato para definir um orçamento.

Obrigado,
Ale
`ale.rossi.ps@icloud.com`

**Comment by steffmartin** [comment]
@azrossi , me desculpe não te responder. Este é um projeto arquivado que eu não acompanho, reconheço que não vi sua dúvida. Espero que tenha resolvido, mas para aqueles que chegarem a esta página, as instruções para utilização do App estão no readme.md. Infelizmente, é um projeto antigo, pode ser que as tecnologias empregadas não estejam mais disponíveis.
